spring.application.name=fitness-monolith


# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/fitness-monolith
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
